import type { Covenant, AuditEntry } from "./types";

/**
 * Seed data ported verbatim from the reference scripts/covenant-data.js (window.COV).
 * createdAt/expiresAt are HARDCODED literal ISO strings — never computed at runtime here.
 */

export const COVENANTS: Covenant[] = [
  {
    id: "#001",
    user: "0x7a3F2c",
    agent: "Research Agent",
    token: "USDC",
    totalBudget: 3.0,
    remainingBudget: 2.75,
    durationHours: 24,
    maxPerRequest: 0.5,
    allowedServices: ["venice.ai", "market-api.demo"],
    purpose: "research-data-purchase",
    createdAt: "2026-05-31T06:00:00Z",
    expiresAt: "2026-06-01T06:00:00Z",
    status: "active",
    color: "#2775ca",
    payments: 1,
  },
  {
    id: "#002",
    user: "0x7a3F2c",
    agent: "Price Monitor",
    token: "USDC",
    totalBudget: 5.0,
    remainingBudget: 0.0,
    durationHours: 168,
    maxPerRequest: 0.25,
    allowedServices: ["market-api.demo"],
    purpose: "price-feed-access",
    createdAt: "2026-05-28T08:00:00Z",
    expiresAt: "2026-06-04T08:00:00Z",
    status: "depleted",
    color: "#2f8f5b",
    payments: 20,
  },
  {
    id: "#003",
    user: "0x7a3F2c",
    agent: "Data Indexer",
    token: "USDC",
    totalBudget: 2.0,
    remainingBudget: 1.4,
    durationHours: 24,
    maxPerRequest: 0.1,
    allowedServices: ["inference.xyz"],
    purpose: "index-metadata",
    createdAt: "2026-05-29T08:00:00Z",
    expiresAt: "2026-05-30T08:00:00Z",
    status: "expired",
    color: "#b08900",
    payments: 6,
  },
  {
    id: "#004",
    user: "0x7a3F2c",
    agent: "Ops Assistant",
    token: "USDC",
    totalBudget: 4.0,
    remainingBudget: 4.0,
    durationHours: 24,
    maxPerRequest: 1.0,
    allowedServices: ["venice.ai"],
    purpose: "ops-automation",
    createdAt: "2026-05-26T08:00:00Z",
    expiresAt: "2026-05-27T08:00:00Z",
    status: "revoked",
    color: "#7e57c2",
    payments: 0,
  },
];

export const AUDIT: AuditEntry[] = [
  {
    id: "aud_001",
    covenantId: "#001",
    task: "ETH short-term risk analysis",
    agent: "Research Agent",
    service: "market-api.demo",
    resource: "ETH sentiment report",
    amount: 0.25,
    decision: "approved",
    reason: "Paid sentiment data required",
    transactionHash: "0x8f3c…a31c",
    execMode: "simulated",
    remainingBudget: 0,
    status: "completed",
    timestamp: "2026-05-31T07:59:00Z",
    timeLabel: "just now",
  },
  {
    id: "aud_002",
    covenantId: "#001",
    task: "News digest summarization",
    agent: "Research Agent",
    service: "news-feed.io",
    resource: "Premium news bundle",
    amount: 0.8,
    decision: "blocked",
    reason: "Price 0.80 exceeds 0.50 per-request limit",
    transactionHash: undefined,
    execMode: "simulated",
    remainingBudget: 0,
    status: "blocked",
    timestamp: "2026-05-31T07:55:00Z",
    timeLabel: "4m ago",
  },
  {
    id: "aud_003",
    covenantId: "#001",
    task: "ETH/BTC volatility compare",
    agent: "Research Agent",
    service: "market-api.demo",
    resource: "Volatility index",
    amount: 0.25,
    decision: "approved",
    reason: "Within budget and purpose",
    transactionHash: "0x2a91…7b0e",
    execMode: "simulated",
    remainingBudget: 0,
    status: "completed",
    timestamp: "2026-05-31T07:41:00Z",
    timeLabel: "18m ago",
  },
  {
    id: "aud_004",
    covenantId: "#003",
    task: "Unverified data fetch",
    agent: "Data Indexer",
    service: "scraper.cheap",
    resource: "Bulk metadata",
    amount: 0.05,
    decision: "blocked",
    reason: "Service not in allowed list",
    transactionHash: undefined,
    execMode: "simulated",
    remainingBudget: 0,
    status: "blocked",
    timestamp: "2026-05-31T06:59:00Z",
    timeLabel: "1h ago",
  },
  {
    id: "aud_005",
    covenantId: "#002",
    task: "Hourly price poll",
    agent: "Price Monitor",
    service: "market-api.demo",
    resource: "Spot price feed",
    amount: 0.25,
    decision: "approved",
    reason: "Scheduled feed access",
    transactionHash: "0x55cd…12af",
    execMode: "simulated",
    remainingBudget: 0,
    status: "completed",
    timestamp: "2026-05-31T06:59:00Z",
    timeLabel: "1h ago",
  },
  {
    id: "aud_006",
    covenantId: "#003",
    task: "Metadata index refresh",
    agent: "Data Indexer",
    service: "inference.xyz",
    resource: "Embedding batch",
    amount: 0.1,
    decision: "approved",
    reason: "Within per-request limit",
    transactionHash: "0x7d2e…9c41",
    execMode: "simulated",
    remainingBudget: 0,
    status: "completed",
    timestamp: "2026-05-31T04:59:00Z",
    timeLabel: "3h ago",
  },
  {
    id: "aud_007",
    covenantId: "#002",
    task: "Final price poll (budget hit)",
    agent: "Price Monitor",
    service: "market-api.demo",
    resource: "Spot price feed",
    amount: 0.25,
    decision: "blocked",
    reason: "Budget depleted — 0.00 remaining",
    transactionHash: undefined,
    execMode: "simulated",
    remainingBudget: 0,
    status: "blocked",
    timestamp: "2026-05-31T01:59:00Z",
    timeLabel: "6h ago",
  },
];

export interface Service {
  name: string;
  cat: string;
  price: string;
  verified: boolean;
  desc: string;
  color: string;
  calls: number;
}

export const SERVICES: Service[] = [
  {
    name: "venice.ai",
    cat: "AI inference & planning",
    price: "0.05–0.40",
    verified: true,
    desc: "Reasoning, task planning and report generation for agents.",
    color: "#7e57c2",
    calls: 42,
  },
  {
    name: "market-api.demo",
    cat: "Market data & sentiment",
    price: "0.25",
    verified: true,
    desc: "Real-time sentiment, volatility and spot-price feeds.",
    color: "#2775ca",
    calls: 31,
  },
  {
    name: "inference.xyz",
    cat: "Model inference",
    price: "0.10",
    verified: true,
    desc: "Embeddings and lightweight inference endpoints.",
    color: "#2f8f5b",
    calls: 6,
  },
  {
    name: "news-feed.io",
    cat: "News & research bundles",
    price: "0.80",
    verified: false,
    desc: "Premium curated news bundles. Exceeds common per-request limits.",
    color: "#b08900",
    calls: 0,
  },
  {
    name: "scraper.cheap",
    cat: "Bulk scraping",
    price: "0.05",
    verified: false,
    desc: "Unverified bulk metadata scraper. Blocked by default policy.",
    color: "#cf4b3e",
    calls: 0,
  },
];
