import { chromium } from "playwright";

const BASE = "http://localhost:3000";
const results = [];
function check(name, cond, extra = "") {
  results.push({ name, ok: !!cond, extra });
  console.log(`${cond ? "PASS" : "FAIL"}  ${name}${extra ? "  — " + extra : ""}`);
}

const browser = await chromium.launch();

async function freshPage() {
  const ctx = await browser.newContext();
  const page = await ctx.newPage();
  page.on("pageerror", (e) => console.log("  [pageerror]", e.message));
  return { ctx, page };
}

// Build a covenant in step 1, optionally tweaking fields, then return at step 2.
async function buildCovenant(page, { maxPer, deselectMarket, purpose } = {}) {
  await page.goto(`${BASE}/new`, { waitUntil: "networkidle" });
  if (maxPer != null) {
    const mp = page.locator('input[type="number"]').nth(1);
    await mp.fill(String(maxPer));
  }
  if (deselectMarket) {
    await page.locator("button.opt", { hasText: "market-api.demo" }).click();
  }
  if (purpose != null) {
    // purpose is the last text input
    const inputs = page.locator('input.input:not([readonly])');
    await inputs.last().fill(purpose);
  }
  await page.getByRole("button", { name: /Sign & create covenant/i }).click();
  await page.getByRole("button", { name: /^Run agent$/i }).waitFor({ timeout: 10000 });
}

async function runAndReachAudit(page) {
  await page.getByRole("button", { name: /^Run agent$/i }).click();
  // wait for the plan card source line
  await page.getByText(/Generated by/i).waitFor({ timeout: 20000 });
}

// ---------- Scenario A: APPROVED ----------
{
  const { ctx, page } = await freshPage();
  await buildCovenant(page); // defaults: maxPer 0.5, market selected, purpose matches
  await runAndReachAudit(page);
  const planBadge = (await page.locator(".rcard .rsub .settle-badge").first().innerText().catch(() => "")).trim();
  check("A: plan card shows AI badge (real/mock)", /real|mock/i.test(planBadge), `badge="${planBadge}"`);
  await page.getByRole("button", { name: /View audit & proof/i }).waitFor({ timeout: 30000 });
  await page.getByRole("button", { name: /View audit & proof/i }).click();
  const h3 = await page.locator(".report .rep-h h3").innerText();
  check("A: audit shows Task complete", /task complete/i.test(h3), `h3="${h3}"`);
  const tl = await page.locator(".timeline .tl").innerText();
  check("A: timeline shows settled", /Payment settled/i.test(tl));
  check("A: timeline NOT blocked", !/blocked/i.test(tl));
  await ctx.close();
}

// ---------- Scenario B: NEEDS_USER (over per-request) ----------
{
  const { ctx, page } = await freshPage();
  await buildCovenant(page, { maxPer: 0.2 }); // 0.25 > 0.2 -> needs_user
  await runAndReachAudit(page);
  const gate = page.getByRole("button", { name: /Approve once & pay/i });
  await gate.waitFor({ timeout: 25000 });
  check("B: approval gate appeared", await gate.isVisible());
  await gate.click();
  await page.getByRole("button", { name: /View audit & proof/i }).waitFor({ timeout: 30000 });
  await page.getByRole("button", { name: /View audit & proof/i }).click();
  const h3 = await page.locator(".report .rep-h h3").innerText();
  check("B: audit shows Task complete (approved once)", /task complete/i.test(h3), `h3="${h3}"`);
  const tl = await page.locator(".timeline .tl").innerText();
  check("B: timeline notes one-time approval", /approved once/i.test(tl));
  await ctx.close();
}

// ---------- Scenario C: BLOCKED (service not allowed) ----------
{
  const { ctx, page } = await freshPage();
  await buildCovenant(page, { deselectMarket: true }); // market-api.demo not allowed -> blocked
  await runAndReachAudit(page);
  // decision card should read blocked
  await page.getByRole("button", { name: /View audit & proof/i }).waitFor({ timeout: 30000 });
  await page.getByRole("button", { name: /View audit & proof/i }).click();
  const h3 = await page.locator(".report .rep-h h3").innerText();
  check("C: audit shows Payment blocked (NOT task complete)", /payment blocked/i.test(h3), `h3="${h3}"`);
  const kv = await page.locator(".report .kv").innerText();
  check("C: payment shows no funds moved", /no funds moved/i.test(kv));
  const tl = await page.locator(".timeline .tl").innerText();
  check("C: timeline shows blocked + no funds", /blocked|No funds moved/i.test(tl));
  await ctx.close();
}

await browser.close();
const failed = results.filter((r) => !r.ok);
console.log(`\n=== ${results.length - failed.length}/${results.length} passed ===`);
process.exit(failed.length ? 1 : 0);
